name: Publish

on: [push]

env:
  DOCKER_BUILDKIT: 1

jobs:
  phpversions:
    name: Build for PHP ${{ matrix.php-versions }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        php: [7.2, 7.3, 7.4]      

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zaherg/laravel-dusk
          add_git_labels: true
          tags: ${{ matrix.php-versions }}
          dockerfile: ./${{ matrix.php-versions }}/Dockerfile

  latest:
    name: Build the latest image

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        php: [7.4]      

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zaherg/laravel-dusk
          add_git_labels: true
          tags: latest
          dockerfile: ./${{ matrix.php-versions }}/Dockerfile          